### ISSUE TITLE
Kerbal Alarm Clock and Mechjeb Do not play nice with Timewarp

### ISSUE THREAD

**Issue by Ruedii** [TriggerAu/KerbalAlarmClock#168]
MechJeb and Kerbal Alarm Clock do not respect each other's changes to time warp.

This should probably be addressed on both ends, as well as making some sort of way that other mods can universally handle time warp so they respect each other's priorities.

I will be reporting this on both Mechjeb and Kerbal Alarm Clock's issue threads, because it is with both of them, and they likely conflict with other mods as well on this..

**Comment by TriggerAu** [comment]
Hey ruedii - can you give me some more info on what you mean by that? As in one is trying to slow time while the other speeds it up?

**Comment by sarbian** [comment]
I guess the common case is MJ warping to a node and a KAC alarm stopping warp.
I added some code in the last dev MJ that will pause all MJ warping if the user or an other mod change the warp. This should do it on my side and I don't think you have anything to do on yours.

**Comment by TriggerAu** [comment]
Ah K thanks for the update @sarbian 

I'll see if there is anything else I can do in that space too - I know in one bit of code I had once the wrp rate changed (and not by the mod) it took its hands off, but I think that might have been some dev code I was going to implement into KAC and removed due to the challenges. I'll double check though to be sure
